apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-local
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app-local
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/alexbarbato/tap-tanzu-java-web-app
      ref:
        branch: main
